spring.application.name=order-service-sample
server.port=8080

# AWS
aws.region=us-east-2

# DynamoDB tables.
orders.table=order-service-orders
orders.table.read-capacity=1
orders.table.write-capacity=1
inventory.table=order-service-inventory
